
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class college extends javax.swing.JFrame {

    /**
     * Creates new form college
     */
    public college() {
        initComponents();
        session s=new session();
        from.setText(s.getusername());
        cname1.setText(s.getusername());
        Connection con;
        ResultSet rst;
        Statement stmt;
               String str="select username from login";
                       try{
         con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rst=stmt.executeQuery(str);
            if(rst.next())
            {
               totxt.setText(rst.getString(1));
            }else{
                JOptionPane.showMessageDialog(this,"no such college exist");
            }
            
    }catch(Exception e){
    }
                       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        viewallsentmsg = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewmsgtbl = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        viewrecievedmsg = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        rmsgtbl = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cname1 = new javax.swing.JTextField();
        search = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cname2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        address2 = new javax.swing.JTextField();
        phone2 = new javax.swing.JTextField();
        uname2 = new javax.swing.JTextField();
        password2 = new javax.swing.JTextField();
        update = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        totxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        message = new javax.swing.JTextArea();
        send = new javax.swing.JButton();
        from = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewallsentmsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewallsentmsg.setText("VIEW SENT MESSAGES");
        viewallsentmsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewallsentmsgActionPerformed(evt);
            }
        });
        jPanel1.add(viewallsentmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 33, 250, -1));

        viewmsgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(viewmsgtbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 72, 419, 120));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\773572510-cloud-computing-icon-computer-app-interface.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 650, 360));

        jTabbedPane1.addTab("sent messages", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        viewrecievedmsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        viewrecievedmsg.setText("VIEW RECIEVED MESSAGES");
        viewrecievedmsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrecievedmsgActionPerformed(evt);
            }
        });
        jPanel2.add(viewrecievedmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 30, -1, -1));

        rmsgtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(rmsgtbl);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 73, -1, 100));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\773572510-cloud-computing-icon-computer-app-interface.jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 340));

        jTabbedPane1.addTab("Recieved messages", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Enter college name");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 20, -1, -1));
        jPanel3.add(cname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 17, 84, -1));

        search.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        search.setText("SEARCH");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        jPanel3.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 16, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("College Name");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 79, -1, -1));
        jPanel3.add(cname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 76, 160, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("address");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 123, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("phoneno");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 168, -1, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("username");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 206, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("password");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 250, -1, -1));

        address2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                address2ActionPerformed(evt);
            }
        });
        jPanel3.add(address2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 160, -1));
        jPanel3.add(phone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 165, 160, -1));
        jPanel3.add(uname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 160, -1));

        password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2ActionPerformed(evt);
            }
        });
        jPanel3.add(password2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 247, 160, -1));

        update.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel3.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\773572510-cloud-computing-icon-computer-app-interface.jpg")); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 350));

        jTabbedPane1.addTab("update college info", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("To");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 31, -1, -1));
        jPanel4.add(totxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 21, 172, 35));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("From");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 74, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Message");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 143, -1, -1));

        message.setColumns(20);
        message.setRows(5);
        jScrollPane3.setViewportView(message);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 125, 218, 114));

        send.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        send.setText("SEND");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });
        jPanel4.add(send, new org.netbeans.lib.awtextra.AbsoluteConstraints(451, 226, -1, -1));

        from.setEditable(false);
        jPanel4.add(from, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 74, 121, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\773572510-cloud-computing-icon-computer-app-interface.jpg")); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 370));

        jTabbedPane1.addTab("compose", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("CONNECT TO CLOUD FOR FILE DOWNLOAD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 69, 350, 50));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\773572510-cloud-computing-icon-computer-app-interface.jpg")); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 780, 340));

        jTabbedPane1.addTab("cloud", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void address2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_address2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_address2ActionPerformed

    private void viewallsentmsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewallsentmsgActionPerformed
        // TODO add your handling code here:
                                                  
        Connection con;
        Statement stmt;
        ResultSet rst;
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            session s=new session();
            rst=stmt.executeQuery("select reciever,sender,message from messages where sender='"+s.getusername()+"'");
            viewmsgtbl.setModel(DbUtils.resultSetToTableModel(rst));
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
            
        }
          
    }//GEN-LAST:event_viewallsentmsgActionPerformed

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        // TODO add your handling code here:
                                                   
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        if(totxt.getText().equals("")){
            JOptionPane.showMessageDialog(this,"to address cannot be empty");
        }else if(from.getText().equals("")){
            JOptionPane.showMessageDialog(this,"From address cannot be empty");
        }else if(message.getText().equals("")){
            JOptionPane.showMessageDialog(this,"message cannot be empty");
        }
        else{
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            int x=stmt.executeUpdate("insert into messages(reciever,sender,message)values('"+totxt.getText()+"','"+from.getText()+"','"+message.getText()+"')");
            if(x!=0)
            {
                JOptionPane.showMessageDialog(this,"Message sent successfully");
            }else{
                JOptionPane.showMessageDialog(this,"Message sent failure");
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e);
        }
        }

    }//GEN-LAST:event_sendActionPerformed

    private void viewrecievedmsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrecievedmsgActionPerformed
        // TODO add your handling code here:
         Connection con;
        Statement stmt;
        ResultSet rst;
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            session s=new session();
            rst=stmt.executeQuery("select reciever,sender,message from messages where reciever='"+s.getusername()+"'");
            rmsgtbl.setModel(DbUtils.resultSetToTableModel(rst));
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
            
        }      
    }//GEN-LAST:event_viewrecievedmsgActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        
        String sql="select * from collegeinfo where cname='"+cname1.getText()+"'";
        if(cname1.getText().equals("")){
            JOptionPane.showMessageDialog(this,"cname cannot be empty");
        }else{
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rst=stmt.executeQuery(sql);
            if(rst.next())
            {
               cname2.setText(rst.getString(1));
                address2.setText(rst.getString(2));
                phone2.setText(rst.getString(3));
                uname2.setText(rst.getString(4));
                 password2.setText(rst.getString(5));
            }else{
                JOptionPane.showMessageDialog(this,"no such college exist");
            }
        }
        
        catch(Exception e)
        {
        JOptionPane.showMessageDialog(this,e);
            
        }
        }
                                         

                                             
       
    }//GEN-LAST:event_searchActionPerformed

    private void password2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2ActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        String str1=cname2.getText();
        String str=phone2.getText();
        String str2=password2.getText();
        if(cname2.getText().equals("")){
            JOptionPane.showMessageDialog(this,"cname cannot be empty");
        }else if(address2.getText().equals("")){
            JOptionPane.showMessageDialog(this,"address cannot be empty");
            
        }else if(phone2.getText().equals("")){
            JOptionPane.showMessageDialog(this,"phoneno cannot be empty");
        }else if(uname2.getText().equals("")){
            JOptionPane.showMessageDialog(this,"username cannot be empty");
        }else if(password2.getText().equals("")){
            JOptionPane.showMessageDialog(this,"password cannot be empty");
        }else{
            
        String sql="update collegeinfo set address='"+address2.getText()+"',phone='"+phone2.getText()+"',username='"+uname2.getText()+"',password='"+password2.getText()+"' where cname='"+cname1.getText()+"'";
        if(!str1.matches("[a-zA-Z_]+")){
                JOptionPane.showMessageDialog(this," cname should not contain numbers");
            }else if(!str.matches("[0-9]+")){
                JOptionPane.showMessageDialog(this,"phone no should not contain alphabets");
            }else if(!str2.matches("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=])(?=\\S+$).{8,}$")){
                JOptionPane.showMessageDialog(this,"invalid password");
            }
            else{
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            int x=stmt.executeUpdate(sql);
            if(x!=0)
            {
                JOptionPane.showMessageDialog(this,"Updated successfully");
                cname2.setText("");
                address2.setText("");
                phone2.setText("");
                uname2.setText("");
                password2.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,e);
        }
        }
        }
    }//GEN-LAST:event_updateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        new Main().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(college.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new college().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address2;
    private javax.swing.JTextField cname1;
    private javax.swing.JTextField cname2;
    private javax.swing.JTextField from;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea message;
    private javax.swing.JTextField password2;
    private javax.swing.JTextField phone2;
    private javax.swing.JTable rmsgtbl;
    private javax.swing.JButton search;
    private javax.swing.JButton send;
    private javax.swing.JTextField totxt;
    private javax.swing.JTextField uname2;
    private javax.swing.JButton update;
    private javax.swing.JButton viewallsentmsg;
    private javax.swing.JTable viewmsgtbl;
    private javax.swing.JButton viewrecievedmsg;
    // End of variables declaration//GEN-END:variables
}
