
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author dell
 */
public class forgotpassword extends javax.swing.JFrame {

    /**
     * Creates new form forgotpassword
     */
    public forgotpassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        question = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\network-3396348_960_720.jpg")); // NOI18N
        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Enter college name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 21, 120, -1));
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 18, 88, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("question");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 85, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("answer");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 132, 50, -1));
        getContentPane().add(answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 129, 185, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setText("Get password");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 199, -1, -1));
        getContentPane().add(question, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 220, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\dell\\Desktop\\773572510-cloud-computing-icon-computer-app-interface.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection con=null;
        Statement stmt=null;
        ResultSet rst=null;
        String str1=question.getText();
        String str2=answer.getText();
       // String sql="select * from collegeinfo where cname='"+cname.getText()+"'and question='"+question.getText()+"' and answer='"+answer.getText()+"'";
        String sql="select * from collegeinfo where question='"+question.getText()+"' and answer='"+answer.getText()+"'";
        //session s =new session();
        //if(s.getusername().equals(cname.getText())){
        try{
            con=ConnectionManager.getConnection();
            stmt=con.createStatement();
            rst=stmt.executeQuery(sql);
            if(rst.next())
            {
                /*if(!str1.equals(rst.getString(7))){
                    JOptionPane.showMessageDialog(this,"question is wrong");
                }else if(!str2.equals(rst.getString(8))){
                    JOptionPane.showMessageDialog(this,"answer is wrong");
                    
                }*/
                if(rst.getString(7).equals(question.getText())){
                    JOptionPane.showMessageDialog(this," question is wrong");
                }else if(rst.getString(8).equals(answer.getText())){
                    JOptionPane.showMessageDialog(this,"answer is wrong");
                }
            }
        else{
                
              //  else{*/
                    if( cname.getText().equals(rst.getString(1)) && question.getText().equals(rst.getString(7)) && answer.getText().equals(rst.getString(8))){
                JOptionPane.showMessageDialog(this,"your password is:"+rst.getString(5));
                //dispose();
                } 
            
            }
            
               /* else
                {
                    JOptionPane.showMessageDialog(this,"question is wrong");
                }*/
                //new login().setVisible(true);
            /*}else if(!question.getText().equals(rst.getString(7))){
                JOptionPane.showMessageDialog(this,"question is wrong");
            }else if(!answer.getText().equals(rst.getString(8))){
                JOptionPane.showMessageDialog(this,"answer is wrong");
            }*///else
           // {
             //   JOptionPane.showMessageDialog(this,"no such college");
            //}

//else{
               // JOptionPane.showMessageDialog(this,"wrong answer");
               // new login().setVisible(true);
            //}
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"wrong question");
        }
        //}
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forgotpassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new forgotpassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answer;
    private javax.swing.JTextField cname;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField question;
    // End of variables declaration//GEN-END:variables
}
